
development:
  adapter: postgresql
  encoding: unicode
  database: Town_Records_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: Town_Records_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: Town_Records_production
  pool: 5
  username:
  password:
